// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvorjprqlxqprhvqhbhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2b3JqcHJxbHhxcHJodnFoYmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNTU4OTgsImV4cCI6MjA2MTYzMTg5OH0.eYQuijjovZ_451l4aJ4FMdp2yoIbZumj0quXefuGzow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);